kind: pipeline
name: default

steps:
  - name: debug
    image: node:lts
    environment:
      SONAR_HOST:
        from_secret: sonar_host
    commands:
      - echo $${SONAR_HOST}
      - echo $SONAR_HOST
  - name: install
    image: node:lts
    commands:
      - yarn install --frozen-lockfile
  - name: generate-icons
    image: node:lts
    commands:
      - yarn generate:icons
  - name: generate-api
    image: timbru31/java-node:8-alpine
    commands:
      - yarn generate:api
  - name: build
    image: node:lts
    commands:
      - yarn build:firefox
  - name: lint
    image: node:lts
    commands:
      - yarn lint:code
      - yarn lint:package
  - name: analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
    when:
      branch:
        - master
