kind: pipeline
name: default

steps:
  - name: install
    image: node:lts
    commands:
      - yarn install --frozen-lockfile
  - name: generate-icons
    image: weboaks/node-karma-protractor-chrome:headless
    privileged: true
    commands:
      - ls -l
      - echo $USER
      - yarn generate:icons
  - name: generate-api
    image: timbru31/java-node:8-alpine
    commands:
      - yarn generate:api
  - name: build
    image: node:lts
    commands:
      - yarn build:firefox
      - yarn lint:code
      - yarn lint:package
