kind: pipeline
name: default

steps:
  - name: build
    image: weboaks/node-karma-protractor-chrome:headless
    commands:
      - apt update && apt install -y openjdk-8-jre-headless
      - yarn install --frozen-lockfile
      - yarn generate:icons
      - yarn generate:api
      - yarn build:firefox
      - yarn lint:code
      - yarn lint:package
